# docker-compose.yml
db:
  image: markwigg/dbpostimg
  ports:
    - "49153:5432"

redis:
  image: redis
  ports:
    - "6379"

sidekiq:
  image: markwigg/push-notify
  command: bundle exec sidekiq RAILS_ENV=production
  links:
    - db
    - redis

web:
  image: markwigg/push-notify
  ports:
    - "80:80"
  # command: bundle exec rails server -b 0.0.0.0
  env_file:
    - .env
  # volumes:
  #     - .:/webapp
  links:
    - db
    - redis
