
proxy:
  image: jwilder/nginx-proxy:latest
  ports:
    - "80:80"
  volumes:
    - "/var/run/docker.sock:/tmp/docker.sock"

db:
  image: markwigg/dbpostimg
  ports:
    - "49153:5432"

redis:
  image: redis

web:
  image: push-notify
  environment:
    VIRTUAL_HOST: localhost
    RAILS_ENV: production
  env_file:
    - 'secrets.env'
  links:
    - db
    - redis
  # volumes:
  #   - .:/home/app/webapp

worker:
  image: push-notify
  command: bundle exec sidekiq -c 25
  environment:
    RAILS_ENV: production
  env_file:
    - 'secrets.env'
  links:
    - db
    - redis
